# Generated by Django 4.1.3 on 2022-12-06 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Краткое описание')),
                ('content', models.TextField(max_length=1000, verbose_name='Контент')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('updated_at', models.DateField(blank=True, null=True, verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
        migrations.AddField(
            model_name='issuemodel',
            name='project',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='webapp.projectmodel', verbose_name='Проекты'),
            preserve_default=False,
        ),
    ]
