# Generated by Django 4.1.3 on 2022-12-23 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0002_projectmodel_issuemodel_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmodel',
            options={'permissions': [('can_add_users_to_the_project', 'Может добавлять пользователей в проект'), ('can_delete_users_to_the_project', 'Может удалять пользователей с проекта')], 'verbose_name': 'Проект', 'verbose_name_plural': 'Проекты'},
        ),
        migrations.AddField(
            model_name='projectmodel',
            name='users',
            field=models.ManyToManyField(related_name='projects', to=settings.AUTH_USER_MODEL, verbose_name='Юзер'),
        ),
    ]
